### ISSUE TITLE
A tutorial asking the user to tap on a letter when it is ready

### ISSUE THREAD

**Issue by Ads20000** [XPRIZE/GLEXP-Team-The-Linguaculturalists#4]
OK, I know I've filed a few of these issues, but you get the jist. Essentially I think the game asks too much of the user in working out how to play the game at the moment. There should be basic tutorial screens stating how to interact with the game in a lot of areas. They don't have to be long, I think Clash of Clans' way of doing this works OK, for example.

The game could point an arrow to the button the user needs to press to complete a certain task (when they have to do that for the first time), this would be an easier way of learning how to play the game.

You might want to close the other tutorial issues and add a checklist instead if you think this is a good idea :)

**Comment by mhall119** [comment]
Thanks for the advice! A tutorial system has been added to walk the player through the various game elements and interactions
