### ISSUE TITLE
A description of the buildings on sale

### ISSUE THREAD

**Issue by Ads20000** [XPRIZE/GLEXP-Team-The-Linguaculturalists#6]
It would be good to have some sort of description/name (a bigger screen for this might be necessary!) for the buildings that are available for purchase. Then the user would know what they are purchasing.

**Comment by mhall119** [comment]
I've reworked the word building selection screen, is this what you had in mind?

![device-2017-01-15-221020](https://cloud.githubusercontent.com/assets/589188/22890192/98a7dbd0-f1d9-11e6-8def-bb3e3f7e52cc.png)

**Comment by Ads20000** [comment]
Something like that but for the shops and the like? There's a few unique buildings that are buildable iirc ( I'm running out of space on my tablet atm so I can't currently test, I'm gonna try and free up some space with an SD card later :) )

**Comment by mhall119** [comment]
You may be thinking of the game buildings and decorations, they both have been updated to add a description. I'm closing this issue for now, but feel free to re-open it or file a new one if you meant something different.
